// GENERATED by assets/gen_tdf_splash.py — do not edit.
// "3D BBS" rendered in 206 TheDraw fonts, as CP437 cell
// grids (char, CGA attribute). See assets/TDF-FONTS-CREDITS.md.
#ifndef TDF_SPLASH_DATA_H
#define TDF_SPLASH_DATA_H

#include <3ds/types.h>

typedef struct {
	u8 w, h;      // cells
	u8 chroma;    // 0-255: share of cells using a non-grey CGA colour.
	              // The collections ship greyscale "silver" variants beside
	              // the colour originals; a low score marks a banner the
	              // splash should tint rather than draw as-is.
	u32 off;      // into tdfCells; w*h pairs of (char, attr)
} TdfBanner;

#define TDF_BANNER_COUNT 206
extern const TdfBanner tdfBanners[TDF_BANNER_COUNT];
extern const u8 tdfCells[];

#endif
